import { css } from "@emotion/react";
import { headline, text } from "@guardian/source-foundations";
import { Button } from "@guardian/source-react-components";
import Head from "next/head";
import Link from "next/link";
import { polls } from "../poll-data";

const pageTitleStyles = css`
  width: 100%;
  margin: 0;

  ${headline.small({ fontWeight: "bold" })}
  font-size: 28px;

  color: ${text.primary};
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Guardian poll project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 css={pageTitleStyles}>Guardian poll project</h1>
        <ul>
          {polls.map((poll) => (
            <li key={poll.id}>
              <Link key={poll.id} href={`/${poll.id}`}>
                {poll.title}
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}
